### ISSUE TITLE
Nested columns?

### ISSUE THREAD

**Issue by rilwis** [justintadlock/grid-columns#10]
Hi,

Thanks for great plugin.

I've just noticed a problem with nested columns. When we make nested columns, the `do_shortcode` function will be called, and then the `column` shortcode runs again.

The problem is we're using singleton pattern, which means the object variables `is_first_column`, `is_last_column`, etc. keep their values between calls. While it's cool non-nested columns, it would be incorrect in nested-columns situation (these variables should be reset at that time).

Hope you can fix it, because it's quite important and needed.

Thanks.

**Comment by justintadlock** [comment]
Nested shortcodes of the same name won't work correctly with WordPress, so this is not something we have to worry about.  See: http://codex.wordpress.org/Shortcode_API#Nested_Shortcodes
