### ISSUE TITLE
Support for Twitter Bootstrap gryd system

### ISSUE THREAD

**Issue by giofilo** [justintadlock/grid-columns#11]
Hi,

I just forked your great plugin and added Twitter Bootstrap classes to row and columns.

https://github.com/giofilo/grid-columns [no longer available]

I'm developing a wp theme based on Bootstrap, and I want to use your plugin too, that's why I made this version of your plugin.
I don't know if you are interested in a pull request of these changes.
Altough you are not, can you please give a look on what I've done with your code? I'm not an expert developer and I would know if I made mistakes.

Thank you very much!

**Comment by justintadlock** [comment]
There are hooks for this sort of thing built right into the plugin.  You can overwrite the classes and dequeue the stylesheet using standard WP methods in a custom plugin or your theme.  The plugin was built so that themes could overwrite this and use whatever grid system they want.

If there are any hooks you need that aren't currently available, I'll be more than happy to look into that.

**Comment by lkraav** [comment]
If you want an example of how to properly plug into GC with whatever grid system you need, see https://github.com/lkraav/wordpress-pure-css

**Comment by giofilo** [comment]
Very helpful! Thanks to both!

**Comment by justintadlock** [comment]
@lkraav Thanks for sharing an example.  I didn't have any on hand.

**Comment by shshaw** [comment]
For anyone else confused by the Pure CSS example above, here an extremely basic syntax for replacing grid-columns' classes with your own, minus any sort of logic that the plugin has.

You can add this to your functions.php file:

```
// Remove grid_column's default stylesheet
add_action( 'wp_enqueue_scripts', "remove_grid_columns_styles");
function remove_grid_columns_styles() {
  if ( class_exists( "Grid_Columns" ) ) {
    wp_dequeue_style('grid-columns');
  }
}

// Override grid_column's classes
add_action( 'init', "filter_grid_columns");
function filter_grid_columns() {
  if ( class_exists( "Grid_Columns" ) ) {
    add_action( "gc_column_class","gc_column_class", 10, 2 );
    add_action( "gc_row_class", "gc_row_class" );
  }
}

function gc_column_class( $classes, $attr ) {
  extract( $attr );
  $class[] = "grid__item";
  $class[] = "size".$span."of".$gridclass;
  $class[] = "push".$push;
  return $class;
}

function gc_row_class() {
  return array("grid");
}
```
