### ISSUE TITLE
Remove `<br>` between columns?

### ISSUE THREAD

**Issue by shshaw** [justintadlock/grid-columns#12]
I prefer to use `text-align: justify`+`display: inline-block` based columns, so I have some style overrides in place. However, if you have spacing between the column declarations, Wordpress inserts a `<br />` tag inbetween.

In the content editor:

```
[column grid="5" span="5"]One Whole[/column]
[column grid="5" span="4"]4/5[/column]
[column grid="5" span="1"]1/5[/column]
```

Thanks to Wordpress's autoparagraph, becomes: 

```
<p><div class="column-grid column-grid-5"><div class="column column-span-5 column-push-0 column-first column-last"><p>One Whole</p>
</div></div><br />
<div class="column-grid column-grid-5"><div class="column column-span-4 column-push-0 column-first"><p>4/5</p>
</div><br />
<div class="column column-span-1 column-push-0 column-last"><p>1/5</p>
</div></div></p>
```

Any conceivable way to remove those `<br />` tags after a column declaration?

**Comment by jayj** [comment]
You could use CSS. 

``` css
.column-grid + br {
   display: none;
}
```

**Comment by shshaw** [comment]
Ah, great idea! That works perfectly. Thanks!
