### ISSUE TITLE
update compatible up to on repo

### ISSUE THREAD

**Issue by ctalkington** [justintadlock/grid-columns#15]
@justintadlock any chance of getting a quick meta bump on the repo for this plugin?

**Comment by justintadlock** [comment]
No chance at all. :) I don't update entire plugins to change a line of text in the readme file. I only update when there are actual code updates.

In the future, I'll remove the data for the "tested up to" line so that it's not an issue.

**Comment by ctalkington** [comment]
understandable, thanks.
