### ISSUE TITLE
Check if there's content within wrapper

### ISSUE THREAD

**Issue by syamilmj** [justintadlock/grid-columns#2]
The column shortcode uses the last span value to determine whether the next column should be a first, middle or last column, and that's very smart.

But a problem would arise if someone for example uses it like this:

[column span=8]Content[/content]

Some content that doesn't belong here

[column span=4]content[/column][column span=8]Content[/column]

**Comment by justintadlock** [comment]
Any solutions you can think of?  My guess is that there's always going to be some problems with a [column] shortcode when people simply don't think about what they're doing.  I've got a few others that I don't see a good workaround for either.

**Comment by Japh** [comment]
Would it be practical to take queues from the way `<table></table>` behaves in this situation?

For example this:

![table html](http://cl.ly/image/1q2R2S0N1P0z/Screen%20Shot%202012-09-18%20at%2013.36.08.png)
(pardon the horrible attributes)

Results in this:

![html output](http://cl.ly/image/0w0T2L1D0S1P/Screen%20Shot%202012-09-18%20at%2013.35.49.png)

**Comment by justintadlock** [comment]
It makes sense, but I can't figure out how to make that happen.

To be honest, after testing the behavior, I don't really see a problem with leaving things as they are.  The content behaves as it should and is positioned where it should be.

**Comment by Japh** [comment]
Sounds like leaving things as they are might be a better solution than "fixing" them then in this case.

**Comment by justintadlock** [comment]
Crap, didn't mean to close this issue.

@Japh That's what I'm thinking right now.  I'll leave this open for anyone who wants to contribute any code for handling it differently.

**Comment by syamilmj** [comment]
In the above example, you'd have problem if the "Some content that doesn't belong here" content consists of other shortcodes that generate div, floats etc.

**Comment by Japh** [comment]
Order may be significant there... but also, at what point is it appropriate to say, "if you do it wrong, it won't work"?

**Comment by mmjaeger** [comment]
How am I supposed to use this within a loop - are there any examples to look at.

Thanks
