### ISSUE TITLE
wpautop() fix in 0.2

### ISSUE THREAD

**Issue by EvGreen** [justintadlock/grid-columns#5]
I've been testing the plugin today, and like it a lot, especially how it checks for first/last column in a row, great idea.

I know you are aware of the issues with wpautop() overdoing things, as I've seen you've added :empty css selector in 0.2, but the problem is that IE8 and lower does not recognize that one, plus ofcourse the empty "p's" are still there, messing with my mild OCD.

Why I find it important to address:
- user selects the content inside the shortcode that he/she wishes to alter: http://img152.imageshack.us/img152/1033/48212c2cb8a44b91aca9c1c.png
- user selects formatting, hoping to alter just the selected piece: http://img267.imageshack.us/img267/7207/9a4509715c8543efa012ced.png
- wordpress formats whole line: http://img715.imageshack.us/img715/3222/ea8d1c10eca544078e106dd.png
- user is confused, so he/she breaks the shortcode into lines: http://i.imgur.com/r0hZDpS.png
- result - wpautop() kicks in, and throws in empty p tags all over the place

Question:
- would adding sniplet like this:

<pre>
if ( '&lt;/p&gt;' == substr( $content, 0, 4 )
and '&lt;p&gt;' == substr( $content, strlen( $content ) - 3 ) )
$content = substr( $content, 4, strlen( $content ) - 7 );
</pre>

inside the do_shortcode function, be advised? It solves the problem, but is it the right thing to do?

cheers!

**Comment by justintadlock** [comment]
In no way, shape, or form do I support IE8 in any of my plugins or themes.

It looks like the things you mentioned above are WordPress-specific issues though.  Core Trac is the best place to go for that.  You'd need to address the problem at the right point in the code.
http://core.trac.wordpress.org/search?q=shortcodes+wpauto
