### ISSUE TITLE
Responsive defaults?

### ISSUE THREAD

**Issue by sebastianschmid** [justintadlock/grid-columns#6]
Hi,
what about adding this to the columns.css:

`@media screen and (max-width: 800px) {
    .column-grid .column {
        float:none;
        margin-left:0;
        margin-right:0;
        width:auto;
    }
}`

What it does, it eliminates all columns below a certain Browser width.

Of course, you could argue, everybody can do his responsive stuff by his own.

But this one could be very convenient if you have no idea about it, and if you do now ... well, you're going to investigate the .css anyway :-)

**Comment by thob** [comment]
I'd love to see this with - say - an optional checkbox on a settings screen

**Comment by sebastianschmid** [comment]
Hi,

das "Problem" hierbei ist  - das grid-columns hat gar keine Konfigurationsseite im Backend. Also würde diese simple checkbox ziemlich viel nach sich ziehen :-)

just my 2 cents :-)

---

S E B A S T I A N  S C H M I D

Web Development

---

T – 43 1 9446793
F – 43 1 25330337777
M – 43 680 3177668

100und1
Kalvarienberggasse 8 / 1-2
1170 Vienna, Austria

follow us on
100und1.com
facebook.com/100und1

---

Am 26.04.2013 um 15:41 schrieb Thomas N. Burg:

> I'd love to see this with - say - an optional checkbox on a settings screen

**Comment by justintadlock** [comment]
I'm not going to get into the details of this at the moment.  However, based on reasons that I've already explained several times in the past, this is not going into the plugin.  When I have a bit more time, I'll dive into a better explanation.

**Comment by lkraav** [comment]
Where is that better explanation going to be posted? I'm interested.
