### ISSUE TITLE
Using has_shortcode

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/grid-columns#9]
Have you thought only loading css when shortcode is in use?

https://codex.wordpress.org/Function_Reference/has_shortcode

http://halgatewood.com/wordpress-3-6-using-has_shortcode-in-wp_head/

That might be handy.

**Comment by justintadlock** [comment]
That solution won't work for a few of reasons.  
- Too late to load styles (scripts OK).  
- Relies on `global $post`, so it doesn't account for non-single pages.
- Relies on the shortcode being in post content (not all shortcode areas are related to the post).

**Sidenote:**

Just as an added thought for scripts, the best way to enqueue them is in the shortcode itself.  Whenever it is executed, enqueue the script in the footer.  This is how you'd properly do it:

```
add_shortcode( 'example', 'my_example_shortcode' );

function my_example_shortcode( $attr ) {

    /* Run shortcode. */

    wp_enqueue_script(); // load script in the footer.
}
```

I'm not sure why folks have other complex solutions.  Nevertheless, that's only going to work for scripts.

**Comment by samikeijonen** [comment]
Thanks for the info. I dequeue styles anyway and put them in theme.

**Comment by justintadlock** [comment]
I'm going to close this for now.  Anyone who has a solution can feel free to add it, and I'll consider re-opening.
